Added a filter option to CLI
LogicalTrust/Keychain-Dumper pull request #1
Opened 2018-01-31 01:35 UTC by brettgervasoni

Allows you to print out entries matching a filter.

2018-01-31 18:51 UTC, mmmds commented
Hi, I've checked your PR. For some filter values I received an exception

`# ./keychain_dumper -f heart   
----------------
Using filter: heart
----------------

Generic Password
----------------
Service: com.apple.account.idms.heartbeat-token
Account: (...)
Entitlement Group: apple
Label: (null)
Keychain protection class: kSecAttrAccessibleAfterFirstUnlock
Generic Field: (...)
Keychain Data: (...)
2018-01-31 19:47:00.870 keychain_dumper[20492:2196400] -[__NSCFData containsString:]: unrecognized selector sent to instance 0x101e1af40
2018-01-31 19:47:00.870 keychain_dumper[20492:2196400] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFData containsString:]: unrecognized selector sent to instance 0x101e1af40'
*** First throw call stack:
(0x184a4d1b8 0x18348455c 0x184a54268 0x184a51270 0x18494a80c 0x100099f14 0x10009af50 0x10009b17c 0x1839095b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6`

Could you check it?

2018-01-31 23:35 UTC, brettgervasoni commented
@mmmds I wasn't able to replicate this with your "heart" filter, but I was able to generate a similar exception on a different key. I've since changed the code a bit, and added a check to make sure the search value is NSString before doing so.

2018-02-01 18:52 UTC, mmmds requested changes
Could you fix indents?

2018-02-01 18:52 UTC, mmmds commented on main.m
> -                printToStdOut(@"Keychain protection class: kSecAttrAccessibleWhenUnlocked\n");
code formatting - following indents

2018-02-01 18:52 UTC, mmmds commented on main.m
> -        if ([[passwordItem objectForKey:(id)kSecAttrAccessible] isEqualToString:@"ck"]) {
code formatting - following indents

2018-02-01 18:53 UTC, mmmds commented
Thanks, now it works. Could you fix code formatting? I've marked places in code.

I use iOS 10.2

2018-02-01 22:28 UTC, notoriousturtle commented
@mmmds Looks all good to me now? 

Have you had any luck running this on iOS 11?

2018-02-02 19:34 UTC, mmmds commented
@brettgervasoni please look at following lines and compare them to the code before your changes:
290 - 304,
333 - 353,
372 - 392,
422 - 442
They are unnecessarily shifted to the left. Please just give them their original indentation.

@notoriousturtle 
I haven't tried on iOS 11.

2018-02-08 03:58 UTC, notoriousturtle commented
The original indentation was off. I thought I fixed them, rather than caused a problem. Looks good for me: https://imgur.com/zvUGnZM

Based on the old code, it looks like you're wanting two tabs before code on each line?

2025-11-06 08:17 UTC, closed without merging